name: Validate LLMS

on:
  pull_request:
    branches:
      - main

jobs:
  check-llms:
    uses: Telucero/workflows/.github/workflows/check-llms.yml@main
    with:
      llms_filename: llms-full.txt
      repo_dir: wormhole-docs
